// ============================================================================
// Equity AI — Financial glossary (Milestone 16C, item 3). Ported verbatim
// from Prototype 1.2 (docs/prototypes/prototype-1.2/
// equity-ai-prototype-1.2.jsx, GLOSSARY / GLOSSARY_ALIASES, lines 58-144) —
// every term key, alias, and definition string is copied exactly as
// reviewed/approved in the prototype. Per the ticket: report any definition
// that reads as absolute, don't rewrite it — see the Milestone 16C report
// for that list (ev_ebitda, estimate_revision_trend, and
// roic_vs_cost_of_capital all read as more certain than the underlying
// claim really is).
//
// Single source of truth: every financial term shown anywhere in the app
// resolves its tooltip from this one object — no component hardcodes its
// own definition text.
// ============================================================================

export interface GlossaryEntry {
  term: string;
  whatIsIt: string;
  whyItMatters: string;
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
  revenue: { term: "Revenue", whatIsIt: "Total sales generated by the company before any costs are subtracted.", whyItMatters: "The starting point for evaluating the size and trajectory of a business." },
  revenue_growth: { term: "Revenue Growth", whatIsIt: "The year-over-year percentage increase in revenue.", whyItMatters: "Shows how quickly the business is expanding — a core driver of long-term value." },
  revenue_cagr: { term: "Revenue CAGR", whatIsIt: "The compound annual growth rate of revenue over a multi-year period, smoothing out single-year noise.", whyItMatters: "Gives a clearer read on the underlying growth trend than any one year alone." },
  eps: { term: "EPS", whatIsIt: "Earnings Per Share — net income divided by the number of shares outstanding.", whyItMatters: "The standard measure of per-share profitability, and the basis for P/E ratios." },
  eps_growth: { term: "EPS Growth", whatIsIt: "The year-over-year percentage change in earnings per share.", whyItMatters: "Shows whether profit growth is keeping pace with — or outpacing — revenue growth." },
  gross_margin: { term: "Gross Margin", whatIsIt: "Revenue minus the direct cost of producing goods or services, shown as a percentage of revenue.", whyItMatters: "Reflects basic pricing power and production efficiency before overhead costs." },
  operating_margin: { term: "Operating Margin", whatIsIt: "Operating profit as a percentage of revenue, after costs like R&D and overhead but before interest and tax.", whyItMatters: "A core measure of how efficiently the core business is run." },
  net_margin: { term: "Net Margin", whatIsIt: "Net income as a percentage of revenue, after all costs, interest and tax.", whyItMatters: "Shows how much of every dollar of sales ultimately becomes profit." },
  roic: { term: "ROIC", whatIsIt: "Return on Invested Capital — how efficiently a company generates operating returns from the capital invested in its business.", whyItMatters: "A high, sustainable ROIC suggests capital is being deployed effectively — especially useful when compared across time or peers." },
  roe: { term: "ROE", whatIsIt: "Return on Equity — net income as a percentage of shareholders' equity.", whyItMatters: "Shows how efficiently a company generates profit from shareholders' capital specifically." },
  free_cash_flow: { term: "Free Cash Flow", whatIsIt: "Cash generated from operations after subtracting capital expenditures.", whyItMatters: "Cash a company can actually use for dividends, buybacks, debt paydown or reinvestment — harder to distort than accounting profit." },
  fcf_margin: { term: "FCF Margin", whatIsIt: "Free cash flow as a percentage of revenue.", whyItMatters: "Shows how much of every dollar of sales converts into cash the company can actually deploy." },
  fcf_yield: { term: "FCF Yield", whatIsIt: "A company's free cash flow relative to its market value.", whyItMatters: "Indicates how much free cash flow investors are getting for the price they're paying." },
  pe: { term: "P/E", whatIsIt: "Price-to-Earnings ratio — the share price divided by earnings per share.", whyItMatters: "A widely used shorthand for how expensive a stock is relative to current profit — most useful compared against peers and history." },
  forward_pe: { term: "Forward P/E", whatIsIt: "How much investors are paying for each unit of a company's expected future earnings.", whyItMatters: "Indicates how highly the market values a company relative to expected future profit. A high Forward P/E can be reasonable when strong growth is expected, but should be considered alongside growth, profitability and risk." },
  ev_ebitda: { term: "EV / EBITDA", whatIsIt: "Enterprise Value divided by EBITDA (earnings before interest, tax, depreciation and amortization).", whyItMatters: "A valuation multiple that, unlike P/E, isn't affected by a company's capital structure or depreciation policy — useful for comparing across companies." },
  ev_sales: { term: "EV / Sales", whatIsIt: "Enterprise Value divided by revenue.", whyItMatters: "Useful for valuing companies that aren't yet consistently profitable, since it doesn't depend on earnings." },
  price_fcf: { term: "Price / FCF", whatIsIt: "Market capitalization divided by free cash flow.", whyItMatters: "Similar to P/E, but based on cash generated rather than accounting earnings, which can be harder to manipulate." },
  net_debt_ebitda: { term: "Net Debt / EBITDA", whatIsIt: "Net debt (total debt minus cash) divided by EBITDA.", whyItMatters: "A common measure of how leveraged a company is relative to its cash-generating ability." },
  debt_equity: { term: "Debt / Equity", whatIsIt: "Total debt divided by shareholders' equity.", whyItMatters: "Shows how much of the business is financed with debt versus owner capital." },
  current_ratio: { term: "Current Ratio", whatIsIt: "Current assets divided by current liabilities.", whyItMatters: "A basic measure of short-term liquidity — whether a company can cover its near-term obligations." },
  interest_coverage: { term: "Interest Coverage", whatIsIt: "Operating income divided by interest expense.", whyItMatters: "Shows how comfortably a company can service its debt from operating profit." },
  share_count: { term: "Share Count", whatIsIt: "The total number of shares outstanding.", whyItMatters: "The denominator behind every per-share figure — EPS, dividends per share, and more." },
  share_count_trend: { term: "Share Count Trend", whatIsIt: "Whether the number of shares outstanding is rising (dilution) or falling (buybacks).", whyItMatters: "A declining share count concentrates each remaining share's claim on future profit; a rising one dilutes it." },
  net_debt: { term: "Net Debt", whatIsIt: "Total debt minus cash and cash equivalents.", whyItMatters: "A cleaner read on financial risk than gross debt alone, since it accounts for cash on hand." },
  net_debt_trend: { term: "Net Debt Trend", whatIsIt: "The direction net debt has moved over recent periods.", whyItMatters: "Shows whether a company is paying down leverage or accumulating it." },
  margin_trend: { term: "Margin Trend", whatIsIt: "The direction a company's margins have moved over recent periods.", whyItMatters: "A single period's margin can be noisy; the trend shows whether profitability is structurally improving or eroding." },
  growth_acceleration: { term: "Growth Acceleration", whatIsIt: "Whether the rate of revenue or earnings growth is speeding up or slowing down.", whyItMatters: "Markets often react more to the direction of growth than to the absolute growth rate itself." },
  guidance: { term: "Guidance", whatIsIt: "Management's own forecast for future financial results, and how consistently the company has met it.", whyItMatters: "Credible, consistently-met guidance is a signal of management quality and forecast reliability." },
  eps_surprise: { term: "EPS Surprise", whatIsIt: "The percentage by which actual EPS beat or missed analyst estimates.", whyItMatters: "A consistent pattern of beats (or misses) can signal how conservative or aggressive expectations have been set." },
  revenue_surprise: { term: "Revenue Surprise", whatIsIt: "The percentage by which actual revenue beat or missed analyst estimates.", whyItMatters: "Shows whether the top line is tracking ahead of or behind what the market expected." },
  estimate_revision_trend: { term: "Estimate Revision Trend", whatIsIt: "The recent direction of analyst estimate changes for a company.", whyItMatters: "Rising estimates often precede price strength; falling estimates often precede weakness." },
  enterprise_value: { term: "Enterprise Value", whatIsIt: "Market capitalization plus net debt — the theoretical takeover cost of a company.", whyItMatters: "A more complete measure of a company's total value than market cap alone, since it accounts for debt and cash." },
  market_cap: { term: "Market Capitalization", whatIsIt: "Share price multiplied by shares outstanding — the total market value of a company's equity.", whyItMatters: "The most common reference point for a company's size." },
  buyback_yield: { term: "Buyback Yield", whatIsIt: "The value of shares repurchased over the past year, as a percentage of market capitalization.", whyItMatters: "Shows how much capital is being returned to shareholders through buybacks specifically." },
  dividend_yield: { term: "Dividend Yield", whatIsIt: "Annual dividends per share divided by share price.", whyItMatters: "Shows the cash return to shareholders from dividends alone, independent of price appreciation." },
  reinvestment_rate: { term: "Reinvestment Rate", whatIsIt: "The share of operating cash flow a company reinvests back into the business.", whyItMatters: "Indicates how much a company is prioritizing future growth versus returning cash to shareholders now." },
  roic_vs_cost_of_capital: { term: "ROIC vs. Cost of Capital", whatIsIt: "The gap between a company's return on invested capital and its cost of capital.", whyItMatters: "Value is created only when ROIC exceeds the cost of capital — the wider the gap, the more efficiently capital is being used." },
  gross_margin_stability: { term: "Gross Margin Stability", whatIsIt: "How consistent a company's gross margin has been over time.", whyItMatters: "Stable margins often indicate pricing power and a durable competitive position." },
  roic_persistence: { term: "ROIC Persistence", whatIsIt: "Whether a company's high returns on invested capital have held up over multiple years, rather than being a one-off.", whyItMatters: "Persistent high ROIC is stronger evidence of a durable competitive advantage than a single good year." },
  rd_intensity: { term: "R&D Intensity", whatIsIt: "Research and development spending as a percentage of revenue.", whyItMatters: "Indicates how much a company is investing in future products and technology relative to its size." },
  customer_concentration: { term: "Customer Concentration", whatIsIt: "How much of a company's revenue comes from its largest customers.", whyItMatters: "High concentration increases risk — losing a major customer can materially affect results." },
  recurring_revenue: { term: "Recurring Revenue", whatIsIt: "The share of revenue that repeats predictably, such as subscriptions, versus one-time sales.", whyItMatters: "Recurring revenue is generally more predictable and higher-quality than one-off sales." },
  subscriber_growth: { term: "Subscriber Growth", whatIsIt: "The year-over-year percentage increase in paying subscribers.", whyItMatters: "The primary growth driver for subscription businesses, feeding directly into future revenue." },
  subscriber_retention: { term: "Subscriber Retention", whatIsIt: "The share of subscribers who remain subscribed over a given period.", whyItMatters: "High retention lowers the cost of sustaining growth, since fewer new subscribers are needed just to offset churn." },
  insider_ownership: { term: "Insider Ownership", whatIsIt: "The percentage of a company's shares held by its executives and directors.", whyItMatters: "Higher insider ownership can align management's incentives more closely with those of shareholders." },
};

/** Maps the exact display labels used throughout the app to a glossary key —
 * the single place label text is connected to its definition, so no
 * component needs to know the glossary's internal keys. Ported verbatim
 * from the prototype's GLOSSARY_ALIASES. */
export const GLOSSARY_ALIASES: Record<string, string> = {
  "Revenue": "revenue", "Revenue ($B)": "revenue",
  "Revenue Growth": "revenue_growth", "Revenue Growth (YoY)": "revenue_growth", "Growth": "revenue_growth",
  "Revenue CAGR": "revenue_cagr", "Revenue CAGR (3Y)": "revenue_cagr",
  "EPS": "eps", "EPS Growth": "eps_growth", "EPS Growth (YoY)": "eps_growth", "EPS CAGR": "eps_growth",
  "Gross Margin": "gross_margin",
  "Operating Margin": "operating_margin",
  "Net Margin": "net_margin",
  "ROIC": "roic", "ROE": "roe",
  "Free Cash Flow": "free_cash_flow", "Free Cash Flow ($B)": "free_cash_flow",
  "FCF Margin": "fcf_margin", "FCF Yield": "fcf_yield",
  "P/E": "pe", "Peer Median P/E": "pe",
  "Forward P/E": "forward_pe",
  "EV / EBITDA": "ev_ebitda", "EV/EBITDA": "ev_ebitda",
  "EV / Sales": "ev_sales",
  "Price / FCF": "price_fcf",
  "Net Debt / EBITDA": "net_debt_ebitda",
  "Debt / Equity": "debt_equity",
  "Current Ratio": "current_ratio",
  "Interest Coverage": "interest_coverage",
  "Share Count": "share_count", "Share Count Trend": "share_count_trend", "Share Dilution Trend": "share_count_trend",
  "Net Debt": "net_debt", "Net Debt Trend": "net_debt_trend",
  "Margin Trend": "margin_trend",
  "Growth Acceleration": "growth_acceleration",
  "Guidance": "guidance", "Guidance Direction": "guidance", "Guidance Credibility": "guidance", "Execution vs. Guidance": "guidance",
  "EPS Surprise": "eps_surprise", "Revenue Surprise": "revenue_surprise",
  "Estimate Revisions": "estimate_revision_trend", "Estimate Revision Trend": "estimate_revision_trend",
  "Enterprise Value": "enterprise_value", "Market Capitalization": "market_cap",
  "Buyback Yield": "buyback_yield", "Dividend Yield": "dividend_yield", "Reinvestment Rate": "reinvestment_rate",
  "ROIC vs. Cost of Capital": "roic_vs_cost_of_capital",
  "Gross Margin Stability": "gross_margin_stability", "ROIC Persistence": "roic_persistence",
  "R&D Intensity": "rd_intensity", "Customer Concentration": "customer_concentration",
  "Recurring Revenue": "recurring_revenue", "Subscriber Growth": "subscriber_growth", "Subscriber Retention": "subscriber_retention",
  "Insider Ownership": "insider_ownership",
};

// The 3 "(YoY)"/"CAGR" entries above with production's exact label text
// ("Revenue Growth (YoY)", "EPS Growth (YoY)", "EPS CAGR" — the prototype's
// own aliases used its shorter "Revenue Growth"/"EPS Growth" label text
// instead) are the only additions beyond a verbatim port of the
// prototype's GLOSSARY_ALIASES, needed so this app's actual label strings
// resolve at all. "Long-Term Debt" (Key Financials) has no glossary entry
// in the prototype and is deliberately left unaliased here rather than
// inventing a new definition.
