import React, { useState, useMemo, useRef } from "react";
import { Search, ChevronRight, ChevronDown, ArrowUp, ArrowDown, Minus, X, Menu, Info } from "lucide-react";

/* ============================================================================
   PROTOTYPE NOTICE — V1.1
   Updated from Prototype V1 per product review feedback: Overview is now
   sparse (identity + score + Why This Score only — Key Financials, Valuation
   summary, AI Thesis and What Changed now live only in their dedicated tabs,
   removing duplication). Upcoming Earnings removed from Dashboard. Opportunity
   Score hidden from the UI (kept in the fixture data). Financial terminology
   now has a centralized, reusable glossary with ⓘ tooltips. Still entirely
   demo-fixture-based — nothing here is connected to FMP, Supabase, or a live
   AI model.
   ========================================================================== */

/* ----------------------------- DESIGN TOKENS -----------------------------
   Restrained, "calm and trustworthy" per spec: white primary, very light
   gray secondary, dark navy text, minimal color used only for meaning. */
const C = {
  bg: "#FFFFFF",
  bgSecondary: "#F7F7F8",
  border: "#E7E8EB",
  text: "#0F1420",
  textSoft: "#5A6072",
  textFaint: "#9DA3B0",
  green: "#1E8E5A",
  greenSoft: "#E9F5EF",
  yellow: "#B7791F",
  yellowSoft: "#FBF3E4",
  red: "#C0432F",
  redSoft: "#FBECE9",
};
const FONT = "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

function scoreLabel(score) {
  if (score >= 85) return "STRONG";
  if (score >= 65) return "MODERATE";
  return "WEAK";
}
function scoreColor(score) {
  if (score >= 85) return C.green;
  if (score >= 65) return C.yellow;
  return C.red;
}
function scoreSoft(score) {
  if (score >= 85) return C.greenSoft;
  if (score >= 65) return C.yellowSoft;
  return C.redSoft;
}

/* ============================================================================
   FINANCIAL GLOSSARY — ONE SOURCE OF TRUTH
   Every financial term shown anywhere in the prototype (Why This Score,
   category deep dives, Financials, Valuation) resolves its ⓘ tooltip from
   this single object. No component hardcodes its own definition text.
   ========================================================================== */

const GLOSSARY = {
  revenue: { term: "Revenue", whatIsIt: "Total sales generated by the company before any costs are subtracted.", whyItMatters: "The starting point for evaluating the size and trajectory of a business." },
  revenue_growth: { term: "Revenue Growth", whatIsIt: "The year-over-year percentage increase in revenue.", whyItMatters: "Shows how quickly the business is expanding — a core driver of long-term value." },
  revenue_cagr: { term: "Revenue CAGR", whatIsIt: "The compound annual growth rate of revenue over a multi-year period, smoothing out single-year noise.", whyItMatters: "Gives a clearer read on the underlying growth trend than any one year alone." },
  eps: { term: "EPS", whatIsIt: "Earnings Per Share — net income divided by the number of shares outstanding.", whyItMatters: "The standard measure of per-share profitability, and the basis for P/E ratios." },
  eps_growth: { term: "EPS Growth", whatIsIt: "The year-over-year percentage change in earnings per share.", whyItMatters: "Shows whether profit growth is keeping pace with — or outpacing — revenue growth." },
  gross_margin: { term: "Gross Margin", whatIsIt: "Revenue minus the direct cost of producing goods or services, shown as a percentage of revenue.", whyItMatters: "Reflects basic pricing power and production efficiency before overhead costs." },
  operating_margin: { term: "Operating Margin", whatIsIt: "Operating profit as a percentage of revenue, after costs like R&D and overhead but before interest and tax.", whyItMatters: "A core measure of how efficiently the core business is run." },
  net_margin: { term: "Net Margin", whatIsIt: "Net income as a percentage of revenue, after all costs, interest and tax.", whyItMatters: "Shows how much of every dollar of sales ultimately becomes profit." },
  roic: { term: "ROIC", whatIsIt: "Return on Invested Capital — how efficiently a company generates operating returns from the capital invested in its business.", whyItMatters: "A high, sustainable ROIC suggests capital is being deployed effectively — especially useful when compared across time or peers." },
  roe: { term: "ROE", whatIsIt: "Return on Equity — net income as a percentage of shareholders' equity.", whyItMatters: "Shows how efficiently a company generates profit from shareholders' capital specifically." },
  free_cash_flow: { term: "Free Cash Flow", whatIsIt: "Cash generated from operations after subtracting capital expenditures.", whyItMatters: "Cash a company can actually use for dividends, buybacks, debt paydown or reinvestment — harder to distort than accounting profit." },
  fcf_margin: { term: "FCF Margin", whatIsIt: "Free cash flow as a percentage of revenue.", whyItMatters: "Shows how much of every dollar of sales converts into cash the company can actually deploy." },
  fcf_yield: { term: "FCF Yield", whatIsIt: "A company's free cash flow relative to its market value.", whyItMatters: "Indicates how much free cash flow investors are getting for the price they're paying." },
  pe: { term: "P/E", whatIsIt: "Price-to-Earnings ratio — the share price divided by earnings per share.", whyItMatters: "A widely used shorthand for how expensive a stock is relative to current profit — most useful compared against peers and history." },
  forward_pe: { term: "Forward P/E", whatIsIt: "How much investors are paying for each unit of a company's expected future earnings.", whyItMatters: "Indicates how highly the market values a company relative to expected future profit. A high Forward P/E can be reasonable when strong growth is expected, but should be considered alongside growth, profitability and risk." },
  ev_ebitda: { term: "EV / EBITDA", whatIsIt: "Enterprise Value divided by EBITDA (earnings before interest, tax, depreciation and amortization).", whyItMatters: "A valuation multiple that, unlike P/E, isn't affected by a company's capital structure or depreciation policy — useful for comparing across companies." },
  ev_sales: { term: "EV / Sales", whatIsIt: "Enterprise Value divided by revenue.", whyItMatters: "Useful for valuing companies that aren't yet consistently profitable, since it doesn't depend on earnings." },
  price_fcf: { term: "Price / FCF", whatIsIt: "Market capitalization divided by free cash flow.", whyItMatters: "Similar to P/E, but based on cash generated rather than accounting earnings, which can be harder to manipulate." },
  net_debt_ebitda: { term: "Net Debt / EBITDA", whatIsIt: "Net debt (total debt minus cash) divided by EBITDA.", whyItMatters: "A common measure of how leveraged a company is relative to its cash-generating ability." },
  debt_equity: { term: "Debt / Equity", whatIsIt: "Total debt divided by shareholders' equity.", whyItMatters: "Shows how much of the business is financed with debt versus owner capital." },
  current_ratio: { term: "Current Ratio", whatIsIt: "Current assets divided by current liabilities.", whyItMatters: "A basic measure of short-term liquidity — whether a company can cover its near-term obligations." },
  interest_coverage: { term: "Interest Coverage", whatIsIt: "Operating income divided by interest expense.", whyItMatters: "Shows how comfortably a company can service its debt from operating profit." },
  share_count: { term: "Share Count", whatIsIt: "The total number of shares outstanding.", whyItMatters: "The denominator behind every per-share figure — EPS, dividends per share, and more." },
  share_count_trend: { term: "Share Count Trend", whatIsIt: "Whether the number of shares outstanding is rising (dilution) or falling (buybacks).", whyItMatters: "A declining share count concentrates each remaining share's claim on future profit; a rising one dilutes it." },
  net_debt: { term: "Net Debt", whatIsIt: "Total debt minus cash and cash equivalents.", whyItMatters: "A cleaner read on financial risk than gross debt alone, since it accounts for cash on hand." },
  net_debt_trend: { term: "Net Debt Trend", whatIsIt: "The direction net debt has moved over recent periods.", whyItMatters: "Shows whether a company is paying down leverage or accumulating it." },
  margin_trend: { term: "Margin Trend", whatIsIt: "The direction a company's margins have moved over recent periods.", whyItMatters: "A single period's margin can be noisy; the trend shows whether profitability is structurally improving or eroding." },
  growth_acceleration: { term: "Growth Acceleration", whatIsIt: "Whether the rate of revenue or earnings growth is speeding up or slowing down.", whyItMatters: "Markets often react more to the direction of growth than to the absolute growth rate itself." },
  guidance: { term: "Guidance", whatIsIt: "Management's own forecast for future financial results, and how consistently the company has met it.", whyItMatters: "Credible, consistently-met guidance is a signal of management quality and forecast reliability." },
  eps_surprise: { term: "EPS Surprise", whatIsIt: "The percentage by which actual EPS beat or missed analyst estimates.", whyItMatters: "A consistent pattern of beats (or misses) can signal how conservative or aggressive expectations have been set." },
  revenue_surprise: { term: "Revenue Surprise", whatIsIt: "The percentage by which actual revenue beat or missed analyst estimates.", whyItMatters: "Shows whether the top line is tracking ahead of or behind what the market expected." },
  estimate_revision_trend: { term: "Estimate Revision Trend", whatIsIt: "The recent direction of analyst estimate changes for a company.", whyItMatters: "Rising estimates often precede price strength; falling estimates often precede weakness." },
  enterprise_value: { term: "Enterprise Value", whatIsIt: "Market capitalization plus net debt — the theoretical takeover cost of a company.", whyItMatters: "A more complete measure of a company's total value than market cap alone, since it accounts for debt and cash." },
  market_cap: { term: "Market Capitalization", whatIsIt: "Share price multiplied by shares outstanding — the total market value of a company's equity.", whyItMatters: "The most common reference point for a company's size." },
  buyback_yield: { term: "Buyback Yield", whatIsIt: "The value of shares repurchased over the past year, as a percentage of market capitalization.", whyItMatters: "Shows how much capital is being returned to shareholders through buybacks specifically." },
  dividend_yield: { term: "Dividend Yield", whatIsIt: "Annual dividends per share divided by share price.", whyItMatters: "Shows the cash return to shareholders from dividends alone, independent of price appreciation." },
  reinvestment_rate: { term: "Reinvestment Rate", whatIsIt: "The share of operating cash flow a company reinvests back into the business.", whyItMatters: "Indicates how much a company is prioritizing future growth versus returning cash to shareholders now." },
  roic_vs_cost_of_capital: { term: "ROIC vs. Cost of Capital", whatIsIt: "The gap between a company's return on invested capital and its cost of capital.", whyItMatters: "Value is created only when ROIC exceeds the cost of capital — the wider the gap, the more efficiently capital is being used." },
  gross_margin_stability: { term: "Gross Margin Stability", whatIsIt: "How consistent a company's gross margin has been over time.", whyItMatters: "Stable margins often indicate pricing power and a durable competitive position." },
  roic_persistence: { term: "ROIC Persistence", whatIsIt: "Whether a company's high returns on invested capital have held up over multiple years, rather than being a one-off.", whyItMatters: "Persistent high ROIC is stronger evidence of a durable competitive advantage than a single good year." },
  rd_intensity: { term: "R&D Intensity", whatIsIt: "Research and development spending as a percentage of revenue.", whyItMatters: "Indicates how much a company is investing in future products and technology relative to its size." },
  customer_concentration: { term: "Customer Concentration", whatIsIt: "How much of a company's revenue comes from its largest customers.", whyItMatters: "High concentration increases risk — losing a major customer can materially affect results." },
  recurring_revenue: { term: "Recurring Revenue", whatIsIt: "The share of revenue that repeats predictably, such as subscriptions, versus one-time sales.", whyItMatters: "Recurring revenue is generally more predictable and higher-quality than one-off sales." },
  subscriber_growth: { term: "Subscriber Growth", whatIsIt: "The year-over-year percentage increase in paying subscribers.", whyItMatters: "The primary growth driver for subscription businesses, feeding directly into future revenue." },
  subscriber_retention: { term: "Subscriber Retention", whatIsIt: "The share of subscribers who remain subscribed over a given period.", whyItMatters: "High retention lowers the cost of sustaining growth, since fewer new subscribers are needed just to offset churn." },
  insider_ownership: { term: "Insider Ownership", whatIsIt: "The percentage of a company's shares held by its executives and directors.", whyItMatters: "Higher insider ownership can align management's incentives more closely with those of shareholders." },
};

/** Maps the exact display labels used throughout the prototype to a glossary
 * key — the single place label text is connected to its definition, so no
 * component needs to know the glossary's internal keys. */
const GLOSSARY_ALIASES = {
  "Revenue": "revenue", "Revenue ($B)": "revenue",
  "Revenue Growth": "revenue_growth", "Growth": "revenue_growth",
  "Revenue CAGR": "revenue_cagr", "Revenue CAGR (3Y)": "revenue_cagr",
  "EPS": "eps", "EPS Growth": "eps_growth",
  "Gross Margin": "gross_margin",
  "Operating Margin": "operating_margin",
  "Net Margin": "net_margin",
  "ROIC": "roic", "ROE": "roe",
  "Free Cash Flow": "free_cash_flow", "Free Cash Flow ($B)": "free_cash_flow",
  "FCF Margin": "fcf_margin", "FCF Yield": "fcf_yield",
  "P/E": "pe", "Peer Median P/E": "pe",
  "Forward P/E": "forward_pe",
  "EV / EBITDA": "ev_ebitda", "EV/EBITDA": "ev_ebitda",
  "EV / Sales": "ev_sales",
  "Price / FCF": "price_fcf",
  "Net Debt / EBITDA": "net_debt_ebitda",
  "Debt / Equity": "debt_equity",
  "Current Ratio": "current_ratio",
  "Interest Coverage": "interest_coverage",
  "Share Count": "share_count", "Share Count Trend": "share_count_trend", "Share Dilution Trend": "share_count_trend",
  "Net Debt": "net_debt", "Net Debt Trend": "net_debt_trend",
  "Margin Trend": "margin_trend",
  "Growth Acceleration": "growth_acceleration",
  "Guidance": "guidance", "Guidance Direction": "guidance", "Guidance Credibility": "guidance", "Execution vs. Guidance": "guidance",
  "EPS Surprise": "eps_surprise", "Revenue Surprise": "revenue_surprise",
  "Estimate Revisions": "estimate_revision_trend", "Estimate Revision Trend": "estimate_revision_trend",
  "Enterprise Value": "enterprise_value", "Market Capitalization": "market_cap",
  "Buyback Yield": "buyback_yield", "Dividend Yield": "dividend_yield", "Reinvestment Rate": "reinvestment_rate",
  "ROIC vs. Cost of Capital": "roic_vs_cost_of_capital",
  "Gross Margin Stability": "gross_margin_stability", "ROIC Persistence": "roic_persistence",
  "R&D Intensity": "rd_intensity", "Customer Concentration": "customer_concentration",
  "Recurring Revenue": "recurring_revenue", "Subscriber Growth": "subscriber_growth", "Subscriber Retention": "subscriber_retention",
  "Insider Ownership": "insider_ownership",
};

/* ============================================================================
   DEMO FIXTURES — NVIDIA, Microsoft, Spotify only, per spec section 20.
   One consistent shape so every component below works for any company
   object, not just NVIDIA.
   ========================================================================== */

const COMPANIES = {
  NVDA: {
    ticker: "NVDA", exchange: "NASDAQ", sector: "Technology", name: "NVIDIA",
    logoInitials: "N", logoColor: "#76B900",
    description: "American technology company focused on GPUs, artificial intelligence and accelerated computing.",
    score: 91, scoreChange: 2.4,
    opportunityScore: 74,
    categories: [
      { key: "growth", name: "Growth", score: 94,
        kpis: [{ label: "Revenue Growth", value: "42%" }, { label: "EPS Growth", value: "46%" }, { label: "Revenue CAGR (3Y)", value: "38%" }, { label: "Growth Acceleration", value: "Improving" }],
        why: "Revenue and earnings are growing well ahead of the company's historical average and its peer group, driven by sustained data center demand.",
        tab: "financials" },
      { key: "profitability", name: "Profitability", score: 97,
        kpis: [{ label: "Gross Margin", value: "75%" }, { label: "Operating Margin", value: "62%" }, { label: "Net Margin", value: "55%" }, { label: "ROIC", value: "41%" }],
        why: "Margins are exceptionally strong and still expanding, reflecting significant pricing power and operating leverage.",
        tab: "financials" },
      { key: "financial_health", name: "Financial Health", score: 88,
        kpis: [{ label: "Net Debt / EBITDA", value: "0.1x" }, { label: "Current Ratio", value: "4.2x" }, { label: "Interest Coverage", value: "112x" }, { label: "Free Cash Flow", value: "$34.2B" }],
        why: "The balance sheet is exceptionally strong, with minimal leverage and ample liquidity.",
        tab: "financials" },
      { key: "valuation", name: "Valuation", score: 72,
        kpis: [{ label: "Forward P/E", value: "31.2" }, { label: "EV / EBITDA", value: "24.8" }, { label: "FCF Yield", value: "2.8%" }, { label: "Peer Median P/E", value: "27.4" }],
        why: "The current multiple prices in continued strong execution, leaving less room for disappointment than the growth and profitability scores alone would suggest.",
        tab: "valuation" },
      { key: "capital_allocation", name: "Capital Allocation", score: 91,
        kpis: [{ label: "Buyback Yield", value: "1.1%" }, { label: "Share Count Trend", value: "Declining" }, { label: "Reinvestment Rate", value: "58%" }, { label: "ROIC vs. Cost of Capital", value: "+33pp" }],
        why: "Capital is being reinvested at returns well above the cost of capital, with disciplined buybacks reducing share count.",
        tab: "analysis" },
      { key: "competitive_advantage", name: "Competitive Advantage", score: 96,
        kpis: [{ label: "Gross Margin Stability", value: "High" }, { label: "ROIC Persistence", value: "5-year high" }, { label: "R&D Intensity", value: "13%" }, { label: "Customer Concentration", value: "Moderate" }],
        why: "Durable margins and persistent high returns on capital point to a strong competitive position in accelerated computing.",
        tab: "analysis" },
      { key: "management", name: "Management", score: 84,
        kpis: [{ label: "Guidance Credibility", value: "High" }, { label: "Insider Ownership", value: "3.5%" }, { label: "Share Dilution Trend", value: "Improving" }, { label: "Execution vs. Guidance", value: "Consistently ahead" }],
        why: "Management has a strong track record of meeting or exceeding its own guidance.",
        tab: "analysis" },
      { key: "earnings_momentum", name: "Earnings Momentum", score: 89,
        kpis: [{ label: "EPS Surprise", value: "+8.1%" }, { label: "Revenue Surprise", value: "+5.4%" }, { label: "Estimate Revisions", value: "Trending up" }, { label: "Guidance Direction", value: "Raised" }],
        why: "Recent results have consistently beaten expectations, and forward estimates are being revised upward.",
        tab: "financials" },
    ],
    keyFinancials: [
      { label: "Revenue", value: "$130.5B" }, { label: "Revenue Growth", value: "+42%" },
      { label: "Operating Margin", value: "62%" }, { label: "Free Cash Flow", value: "$34.2B" }, { label: "ROIC", value: "41%" },
    ],
    financialsHistory: [
      { year: "FY23", revenue: 60.9, growth: 26, opMargin: 54, fcf: 27.0 },
      { year: "FY24", revenue: 96.3, growth: 58, opMargin: 58, fcf: 27.0 },
      { year: "FY25", revenue: 130.5, growth: 42, opMargin: 62, fcf: 34.2 },
    ],
    valuation: { forwardPE: 31.2, peerMedianPE: 27.4, fcfYield: "2.8%", score: 72,
      multiples: [
        { label: "Forward P/E", value: "31.2", peerMedian: "27.4", historicalAvg: "34.6" },
        { label: "EV / EBITDA", value: "24.8", peerMedian: "19.2", historicalAvg: "28.1" },
        { label: "EV / Sales", value: "17.9", peerMedian: "8.4", historicalAvg: "19.5" },
        { label: "Price / FCF", value: "35.1", peerMedian: "26.7", historicalAvg: "38.2" },
      ],
      peers: [
        { name: "AMD", pe: "38.5", evEbitda: "29.1" },
        { name: "Broadcom", pe: "26.8", evEbitda: "18.4" },
        { name: "Intel", pe: "—", evEbitda: "12.6" },
      ] },
    thesis: {
      summary: "NVIDIA combines exceptional growth, profitability and competitive positioning, while its valuation leaves less room for execution disappointments.",
      bull: "Data center demand continues to outpace supply through the next several product cycles, sustaining both growth and margins near current levels.",
      base: "Growth decelerates toward a still-elevated rate as the comparison base grows, with margins holding roughly flat.",
      bear: "A demand air-pocket or a faster-than-expected competitive response compresses margins and re-rates the multiple sharply lower.",
      risks: ["Customer concentration among a small number of hyperscalers", "Export policy changes affecting addressable market", "Competitive response from custom silicon programs"],
      catalysts: ["Next quarterly earnings report", "New data center product cycle commentary", "Major hyperscaler capex guidance updates"],
    },
    changes: [
      { color: "green", metric: "Revenue Growth", from: "38%", to: "42%", date: "2 days ago" },
      { color: "green", metric: "Operating Margin", from: "59%", to: "62%", date: "2 days ago" },
      { color: "red", metric: "Forward P/E", from: "27", to: "31", date: "5 days ago" },
      { color: "green", metric: "Free Cash Flow", from: "$29.1B", to: "$34.2B", date: "1 week ago" },
      { color: "yellow", metric: "Insider Ownership", from: "3.7%", to: "3.5%", date: "2 weeks ago" },
    ],
    sources: {
      "Revenue Growth": { source: "Company Filing", period: "Q2 2026" },
      "Operating Margin": { source: "Company Filing", period: "Q2 2026" },
      "Forward P/E": { source: "Market Data", period: "As of today" },
    },
    upcomingEarnings: { date: "Feb 25, 2027", note: "FY27 Q4 earnings" },
  },

  MSFT: {
    ticker: "MSFT", exchange: "NASDAQ", sector: "Technology", name: "Microsoft",
    logoInitials: "M", logoColor: "#5E5CE6",
    description: "American technology company providing cloud computing, productivity software and enterprise services.",
    score: 87, scoreChange: -0.8,
    opportunityScore: 70,
    categories: [
      { key: "growth", name: "Growth", score: 78, kpis: [{ label: "Revenue Growth", value: "16%" }, { label: "EPS Growth", value: "18%" }, { label: "Revenue CAGR (3Y)", value: "15%" }, { label: "Growth Acceleration", value: "Stable" }],
        why: "Growth has moderated from prior years but remains durable and broad-based across cloud and productivity segments.", tab: "financials" },
      { key: "profitability", name: "Profitability", score: 91, kpis: [{ label: "Gross Margin", value: "69%" }, { label: "Operating Margin", value: "45%" }, { label: "Net Margin", value: "36%" }, { label: "ROIC", value: "28%" }],
        why: "Margins remain consistently high across a diversified business.", tab: "financials" },
      { key: "financial_health", name: "Financial Health", score: 96, kpis: [{ label: "Net Debt / EBITDA", value: "0.3x" }, { label: "Current Ratio", value: "1.9x" }, { label: "Interest Coverage", value: "45x" }, { label: "Free Cash Flow", value: "$74.1B" }],
        why: "The balance sheet is exceptionally strong with very low leverage.", tab: "financials" },
      { key: "valuation", name: "Valuation", score: 74, kpis: [{ label: "Forward P/E", value: "29.6" }, { label: "EV / EBITDA", value: "21.3" }, { label: "FCF Yield", value: "2.4%" }, { label: "Peer Median P/E", value: "26.1" }],
        why: "Valuation sits above peer median, reflecting the market's confidence in durable cloud growth.", tab: "valuation" },
      { key: "capital_allocation", name: "Capital Allocation", score: 90, kpis: [{ label: "Dividend Yield", value: "0.7%" }, { label: "Buyback Yield", value: "0.9%" }, { label: "Reinvestment Rate", value: "62%" }, { label: "ROIC vs. Cost of Capital", value: "+21pp" }],
        why: "Capital allocation is disciplined, balancing reinvestment, dividends and buybacks.", tab: "analysis" },
      { key: "competitive_advantage", name: "Competitive Advantage", score: 92, kpis: [{ label: "Gross Margin Stability", value: "High" }, { label: "ROIC Persistence", value: "Stable" }, { label: "R&D Intensity", value: "12%" }, { label: "Recurring Revenue", value: "~85%" }],
        why: "High recurring revenue and switching costs across enterprise software support a durable position.", tab: "analysis" },
      { key: "management", name: "Management", score: 89, kpis: [{ label: "Guidance Credibility", value: "High" }, { label: "Insider Ownership", value: "0.1%" }, { label: "Share Dilution Trend", value: "Flat" }, { label: "Execution vs. Guidance", value: "Consistent" }],
        why: "Management has a long track record of consistent execution against guidance.", tab: "analysis" },
      { key: "earnings_momentum", name: "Earnings Momentum", score: 80, kpis: [{ label: "EPS Surprise", value: "+3.2%" }, { label: "Revenue Surprise", value: "+1.8%" }, { label: "Estimate Revisions", value: "Stable" }, { label: "Guidance Direction", value: "Maintained" }],
        why: "Recent results were roughly in line with expectations.", tab: "financials" },
    ],
    keyFinancials: [
      { label: "Revenue", value: "$245.1B" }, { label: "Revenue Growth", value: "+16%" },
      { label: "Operating Margin", value: "45%" }, { label: "Free Cash Flow", value: "$74.1B" }, { label: "ROIC", value: "28%" },
    ],
    financialsHistory: [
      { year: "FY23", revenue: 211.9, growth: 7, opMargin: 42, fcf: 59.5 },
      { year: "FY24", revenue: 227.6, growth: 7, opMargin: 44, fcf: 65.1 },
      { year: "FY25", revenue: 245.1, growth: 16, opMargin: 45, fcf: 74.1 },
    ],
    valuation: { forwardPE: 29.6, peerMedianPE: 26.1, fcfYield: "2.4%", score: 74,
      multiples: [
        { label: "Forward P/E", value: "29.6", peerMedian: "26.1", historicalAvg: "31.0" },
        { label: "EV / EBITDA", value: "21.3", peerMedian: "17.5", historicalAvg: "22.6" },
        { label: "EV / Sales", value: "11.2", peerMedian: "7.1", historicalAvg: "12.4" },
        { label: "Price / FCF", value: "31.8", peerMedian: "25.0", historicalAvg: "33.4" },
      ],
      peers: [{ name: "Google", pe: "24.9", evEbitda: "16.8" }, { name: "Amazon", pe: "33.1", evEbitda: "14.2" }, { name: "Apple", pe: "28.4", evEbitda: "20.5" }] },
    thesis: {
      summary: "Microsoft's financial health and quality remain exceptional, underpinned by cloud and productivity segments, though growth has moderated from prior years.",
      bull: "Cloud reacceleration alongside AI-attached productivity revenue lifts growth back toward the high teens.",
      base: "Growth holds in the mid-teens with continued margin discipline across segments.",
      bear: "Enterprise IT spending softens broadly, slowing cloud growth alongside the rest of the sector.",
      risks: ["Elevated capex intensity pressuring near-term free cash flow", "Regulatory scrutiny across major markets"],
      catalysts: ["Cloud segment growth disclosure next quarter", "AI-attached revenue commentary"],
    },
    changes: [
      { color: "yellow", metric: "Revenue Growth", from: "17%", to: "16%", date: "3 days ago" },
      { color: "green", metric: "Free Cash Flow", from: "$68.4B", to: "$74.1B", date: "1 week ago" },
      { color: "red", metric: "Forward P/E", from: "27.9", to: "29.6", date: "1 week ago" },
    ],
    sources: {
      "Revenue Growth": { source: "Company Filing", period: "Q2 2026" },
      "Forward P/E": { source: "Market Data", period: "As of today" },
    },
    upcomingEarnings: { date: "Jan 27, 2027", note: "FY27 Q2 earnings" },
  },

  SPOT: {
    ticker: "SPOT", exchange: "NYSE", sector: "Communication Services", name: "Spotify",
    logoInitials: "S", logoColor: "#1ED760",
    description: "Swedish audio streaming company offering music, podcasts and audiobooks through subscription and ad-supported tiers.",
    score: 82, scoreChange: 4.1,
    opportunityScore: 79,
    categories: [
      { key: "growth", name: "Growth", score: 74, kpis: [{ label: "Revenue Growth", value: "19%" }, { label: "EPS Growth", value: "—" }, { label: "Subscriber Growth", value: "12%" }, { label: "Growth Acceleration", value: "Improving" }],
        why: "Subscriber growth is reaccelerating, supporting durable revenue growth.", tab: "financials" },
      { key: "profitability", name: "Profitability", score: 68, kpis: [{ label: "Gross Margin", value: "31%" }, { label: "Operating Margin", value: "11%" }, { label: "Net Margin", value: "8%" }, { label: "ROIC", value: "14%" }],
        why: "Profitability is improving from a historically low base as subscriber growth outpaces content costs.", tab: "financials" },
      { key: "financial_health", name: "Financial Health", score: 79, kpis: [{ label: "Net Debt / EBITDA", value: "0.4x" }, { label: "Current Ratio", value: "1.6x" }, { label: "Interest Coverage", value: "18x" }, { label: "Free Cash Flow", value: "$2.1B" }],
        why: "The balance sheet is solid, with manageable leverage and improving cash generation.", tab: "financials" },
      { key: "valuation", name: "Valuation", score: 85, kpis: [{ label: "Forward P/E", value: "34.4" }, { label: "EV / EBITDA", value: "22.6" }, { label: "FCF Yield", value: "2.9%" }, { label: "Peer Median P/E", value: "38.1" }],
        why: "Trades at a discount to peers despite an improving margin trajectory.", tab: "valuation" },
      { key: "capital_allocation", name: "Capital Allocation", score: 71, kpis: [{ label: "Buyback Yield", value: "0.3%" }, { label: "Share Count Trend", value: "Roughly flat" }, { label: "Reinvestment Rate", value: "70%" }, { label: "ROIC vs. Cost of Capital", value: "+5pp" }],
        why: "Capital is primarily reinvested into content and platform expansion.", tab: "analysis" },
      { key: "competitive_advantage", name: "Competitive Advantage", score: 76, kpis: [{ label: "Gross Margin Stability", value: "Improving" }, { label: "ROIC Persistence", value: "Early trend" }, { label: "R&D Intensity", value: "8%" }, { label: "Subscriber Retention", value: "High" }],
        why: "Strong subscriber retention and a growing catalog support a durable, if still-developing, moat.", tab: "analysis" },
      { key: "management", name: "Management", score: 73, kpis: [{ label: "Guidance Credibility", value: "Moderate" }, { label: "Insider Ownership", value: "22%" }, { label: "Share Dilution Trend", value: "Stable" }, { label: "Execution vs. Guidance", value: "Improving" }],
        why: "High insider ownership aligns management with shareholders; guidance track record is improving.", tab: "analysis" },
      { key: "earnings_momentum", name: "Earnings Momentum", score: 88, kpis: [{ label: "EPS Surprise", value: "+14%" }, { label: "Revenue Surprise", value: "+3.1%" }, { label: "Estimate Revisions", value: "Trending up" }, { label: "Guidance Direction", value: "Raised" }],
        why: "Recent results have beaten expectations by a wide margin, driving upward estimate revisions.", tab: "financials" },
    ],
    keyFinancials: [
      { label: "Revenue", value: "$16.8B" }, { label: "Revenue Growth", value: "+19%" },
      { label: "Operating Margin", value: "11%" }, { label: "Free Cash Flow", value: "$2.1B" }, { label: "ROIC", value: "14%" },
    ],
    financialsHistory: [
      { year: "FY23", revenue: 13.2, growth: 13, opMargin: 2, fcf: 0.6 },
      { year: "FY24", revenue: 14.6, growth: 11, opMargin: 8, fcf: 1.3 },
      { year: "FY25", revenue: 16.8, growth: 19, opMargin: 11, fcf: 2.1 },
    ],
    valuation: { forwardPE: 34.4, peerMedianPE: 38.1, fcfYield: "2.9%", score: 85,
      multiples: [
        { label: "Forward P/E", value: "34.4", peerMedian: "38.1", historicalAvg: "41.2" },
        { label: "EV / EBITDA", value: "22.6", peerMedian: "24.0", historicalAvg: "27.8" },
        { label: "EV / Sales", value: "3.4", peerMedian: "5.2", historicalAvg: "3.9" },
        { label: "Price / FCF", value: "27.1", peerMedian: "29.4", historicalAvg: "33.0" },
      ],
      peers: [{ name: "Netflix", pe: "41.2", evEbitda: "26.4" }, { name: "Warner Bros Discovery", pe: "—", evEbitda: "9.8" }] },
    thesis: {
      summary: "Spotify's profitability is inflecting faster than expected off a still-early base, and current valuation sits at a discount to peers.",
      bull: "Margin expansion continues at the current pace as pricing power and ad-supported monetization both improve.",
      base: "Margin gains continue but at a slower pace as content costs re-accelerate with catalog growth.",
      bear: "Subscriber growth slows in a more competitive streaming landscape, stalling the margin inflection.",
      risks: ["Content cost inflation", "Competitive pricing pressure from larger platforms"],
      catalysts: ["Next quarterly subscriber and margin update", "Audiobook and podcast monetization commentary"],
    },
    changes: [
      { color: "green", metric: "Operating Margin", from: "8%", to: "11%", date: "2 days ago" },
      { color: "green", metric: "Subscriber Growth", from: "9%", to: "12%", date: "4 days ago" },
      { color: "yellow", metric: "Forward P/E", from: "32.1", to: "34.4", date: "1 week ago" },
    ],
    sources: {
      "Operating Margin": { source: "Company Filing", period: "Q2 2026" },
      "Subscriber Growth": { source: "Company Filing", period: "Q2 2026" },
    },
    upcomingEarnings: { date: "Jan 30, 2027", note: "Q4 2026 earnings" },
  },
};

/* ----------------------------- SMALL PRIMITIVES ----------------------------- */

function ChangeTag({ value }) {
  const v = typeof value === "number" ? value : parseFloat(value);
  const isPos = v > 0, isZero = v === 0 || Number.isNaN(v);
  const color = isZero ? C.textFaint : isPos ? C.green : C.red;
  const Icon = isZero ? Minus : isPos ? ArrowUp : ArrowDown;
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 3, color, fontSize: 12.5, fontWeight: 600 }}>
      <Icon size={11} strokeWidth={2.5} />
      {isZero ? "0" : `${Math.abs(v)}${typeof value === "number" ? "" : ""}`}
    </span>
  );
}

function ColorDot({ color }) {
  const map = { green: C.green, yellow: C.yellow, red: C.red };
  return <span style={{ width: 7, height: 7, borderRadius: 999, backgroundColor: map[color], display: "inline-block", flexShrink: 0 }} />;
}

function DemoTag() {
  return (
    <span style={{ fontSize: 10.5, fontWeight: 600, color: C.textFaint, border: `1px solid ${C.border}`, borderRadius: 5, padding: "2px 6px", letterSpacing: "0.03em" }}>
      PROTOTYPE · DEMO DATA
    </span>
  );
}

function CompanyLogo({ company, size = 40 }) {
  return (
    <div style={{
      width: size, height: size, borderRadius: size * 0.28, backgroundColor: company.logoColor, flexShrink: 0,
      display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: size * 0.42,
    }}>
      {company.logoInitials}
    </div>
  );
}

function SourceNote({ metricLabel, company }) {
  const s = company.sources?.[metricLabel];
  if (!s) return null;
  return <div style={{ fontSize: 10.5, color: C.textFaint, marginTop: 3 }}>Source: {s.source} · {s.period}</div>;
}

/* ----------------------------- FINANCIAL TERMINOLOGY TOOLTIPS -----------------------------
   Single reusable ⓘ + popover, driven entirely by GLOSSARY / GLOSSARY_ALIASES
   above — no component defines its own tooltip text. Opens on click/tap (not
   hover-only, so it works on touch devices) and closes on an outside tap. */

function InfoIcon({ termKey }) {
  const [open, setOpen] = useState(false);
  const [pos, setPos] = useState({ top: 0, left: 0 });
  const btnRef = useRef(null);
  const entry = GLOSSARY[termKey];
  if (!entry) return null;

  const toggle = (e) => {
    e.stopPropagation();
    if (!open && btnRef.current) {
      const rect = btnRef.current.getBoundingClientRect();
      const popWidth = 260;
      let left = rect.left;
      if (left + popWidth > window.innerWidth - 12) left = window.innerWidth - popWidth - 12;
      setPos({ top: rect.bottom + 6, left: Math.max(12, left) });
    }
    setOpen((o) => !o);
  };

  return (
    <span style={{ position: "relative", display: "inline-flex", verticalAlign: "middle" }}>
      <button ref={btnRef} onClick={toggle} aria-label={`What does ${entry.term} mean?`} style={{
        border: "none", background: "none", cursor: "pointer", padding: 2, marginLeft: 3, color: C.textFaint,
        display: "inline-flex", alignItems: "center", justifyContent: "center", borderRadius: 999,
      }}>
        <Info size={12} strokeWidth={2} />
      </button>
      {open && (
        <>
          <div onClick={() => setOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 199 }} />
          <div onClick={(e) => e.stopPropagation()} style={{
            position: "fixed", top: pos.top, left: pos.left, width: 260, zIndex: 200,
            backgroundColor: C.bg, border: `1px solid ${C.border}`, borderRadius: 10, padding: 14,
            boxShadow: "0 10px 30px rgba(15,20,32,0.14)",
          }}>
            <div style={{ fontSize: 12.5, fontWeight: 700, color: C.text, marginBottom: 8 }}>{entry.term}</div>
            <div style={{ fontSize: 10, fontWeight: 700, color: C.textFaint, letterSpacing: "0.05em", marginBottom: 3 }}>WHAT IS IT?</div>
            <p style={{ fontSize: 12, color: C.textSoft, lineHeight: 1.5, margin: "0 0 10px" }}>{entry.whatIsIt}</p>
            <div style={{ fontSize: 10, fontWeight: 700, color: C.textFaint, letterSpacing: "0.05em", marginBottom: 3 }}>WHY IT MATTERS</div>
            <p style={{ fontSize: 12, color: C.textSoft, lineHeight: 1.5, margin: 0 }}>{entry.whyItMatters}</p>
          </div>
        </>
      )}
    </span>
  );
}

/** Wraps a metric label with its ⓘ tooltip, resolved from GLOSSARY_ALIASES.
 * If a label has no glossary entry, it just renders as plain text — adding
 * a tooltip is opt-in via the glossary, never assumed. */
function FinancialTerm({ label, style }) {
  const key = GLOSSARY_ALIASES[label];
  return (
    <span style={{ display: "inline-flex", alignItems: "center", ...style }}>
      {label}
      {key && <InfoIcon termKey={key} />}
    </span>
  );
}

/* ----------------------------- NAVIGATION ----------------------------- */

const SIDEBAR_SECTIONS = [
  { label: "RESEARCH", items: [{ key: "dashboard", label: "Dashboard" }, { key: "discover", label: "Discover" }] },
  { label: "PORTFOLIO", items: [{ key: "watchlist", label: "Watchlist" }, { key: "companies", label: "Companies" }] },
  { label: "MONITORING", items: [{ key: "alerts", label: "Alerts" }] },
  { label: "SETTINGS", items: [{ key: "settings", label: "Settings" }] },
];

function Sidebar({ view, setView }) {
  return (
    <div className="hidden md:flex" style={{ width: 216, flexShrink: 0, borderRight: `1px solid ${C.border}`, flexDirection: "column", height: "100vh", position: "sticky", top: 0, backgroundColor: C.bg }}>
      <div style={{ padding: "24px 22px 20px" }}>
        <div style={{ fontSize: 14.5, fontWeight: 700, color: C.text, letterSpacing: "0.02em" }}>EQUITY AI</div>
      </div>
      <nav style={{ padding: "0 14px", display: "flex", flexDirection: "column", gap: 22, overflowY: "auto" }}>
        {SIDEBAR_SECTIONS.map((section) => (
          <div key={section.label}>
            <div style={{ fontSize: 10.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em", padding: "0 10px 6px" }}>{section.label}</div>
            {section.items.map((item) => {
              const active = view === item.key;
              return (
                <button key={item.key} onClick={() => setView(item.key)} style={{
                  display: "block", width: "100%", textAlign: "left", padding: "7px 10px", borderRadius: 6, border: "none", cursor: "pointer",
                  backgroundColor: active ? C.bgSecondary : "transparent", color: active ? C.text : C.textSoft,
                  fontSize: 13.5, fontWeight: active ? 600 : 500, marginBottom: 1,
                }}>
                  {item.label}
                </button>
              );
            })}
          </div>
        ))}
      </nav>
    </div>
  );
}

function MobileTopBar({ view, setView, mobileOpen, setMobileOpen }) {
  return (
    <div className="flex md:hidden" style={{ alignItems: "center", justifyContent: "space-between", padding: "14px 18px", borderBottom: `1px solid ${C.border}`, backgroundColor: C.bg, position: "sticky", top: 0, zIndex: 40 }}>
      <div style={{ fontSize: 14, fontWeight: 700, color: C.text, letterSpacing: "0.02em" }}>EQUITY AI</div>
      <button onClick={() => setMobileOpen(!mobileOpen)} style={{ border: "none", background: "none", cursor: "pointer", color: C.text, padding: 4 }}>
        {mobileOpen ? <X size={19} /> : <Menu size={19} />}
      </button>
      {mobileOpen && (
        <div style={{ position: "absolute", top: "100%", left: 0, right: 0, backgroundColor: C.bg, borderBottom: `1px solid ${C.border}`, padding: "8px 14px 16px", boxShadow: "0 8px 20px rgba(15,20,32,0.06)" }}>
          {SIDEBAR_SECTIONS.map((section) => (
            <div key={section.label} style={{ marginTop: 14 }}>
              <div style={{ fontSize: 10.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em", padding: "0 6px 6px" }}>{section.label}</div>
              {section.items.map((item) => (
                <button key={item.key} onClick={() => { setView(item.key); setMobileOpen(false); }} style={{
                  display: "block", width: "100%", textAlign: "left", padding: "9px 6px", borderRadius: 6, border: "none", cursor: "pointer",
                  backgroundColor: view === item.key ? C.bgSecondary : "transparent", color: view === item.key ? C.text : C.textSoft,
                  fontSize: 14, fontWeight: view === item.key ? 600 : 500,
                }}>
                  {item.label}
                </button>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/* ----------------------------- SEARCH ----------------------------- */

function SearchField({ value, onChange, onFocus, placeholder }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 10, padding: "12px 16px", border: `1px solid ${C.border}`, borderRadius: 10, backgroundColor: C.bg }}>
      <Search size={16} color={C.textFaint} strokeWidth={2} />
      <input value={value} onChange={(e) => onChange(e.target.value)} onFocus={onFocus} placeholder={placeholder}
        style={{ border: "none", outline: "none", fontSize: 14.5, flex: 1, color: C.text, backgroundColor: "transparent", fontFamily: FONT }} />
    </div>
  );
}

function SearchView({ recentSearches, goToCompany }) {
  const [query, setQuery] = useState("");
  const all = Object.values(COMPANIES);
  const results = useMemo(() => {
    if (!query.trim()) return [];
    const q = query.toLowerCase();
    return all.filter((c) => c.name.toLowerCase().includes(q) || c.ticker.toLowerCase().includes(q));
  }, [query]);

  return (
    <div style={{ maxWidth: 560 }}>
      <div style={{ fontSize: 11.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em", marginBottom: 12 }}>SEARCH A COMPANY OR TICKER</div>
      <SearchField value={query} onChange={setQuery} placeholder="e.g. NVIDIA or NVDA" />

      {!query.trim() && recentSearches.length > 0 && (
        <div style={{ marginTop: 30 }}>
          <div style={{ fontSize: 11.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em", marginBottom: 10 }}>RECENT SEARCHES</div>
          {recentSearches.map((ticker) => {
            const c = COMPANIES[ticker];
            if (!c) return null;
            return (
              <button key={ticker} onClick={() => goToCompany(ticker)} style={{ display: "block", width: "100%", textAlign: "left", padding: "10px 4px", border: "none", background: "none", cursor: "pointer", borderBottom: `1px solid ${C.border}`, fontSize: 14.5, color: C.text, fontWeight: 500 }}>
                {c.name}
              </button>
            );
          })}
        </div>
      )}

      {query.trim() && (
        <div style={{ marginTop: 24 }}>
          {results.length === 0 ? (
            <p style={{ fontSize: 13, color: C.textFaint }}>No matches in this prototype's demo dataset (NVIDIA, Microsoft, Spotify).</p>
          ) : results.map((c) => (
            <button key={c.ticker} onClick={() => goToCompany(c.ticker)} style={{
              display: "flex", alignItems: "center", gap: 12, width: "100%", textAlign: "left", padding: "12px 4px",
              border: "none", background: "none", cursor: "pointer", borderBottom: `1px solid ${C.border}`,
            }}>
              <CompanyLogo company={c} size={32} />
              <div>
                <div style={{ fontSize: 14.5, fontWeight: 600, color: C.text }}>{c.name}</div>
                <div style={{ fontSize: 12, color: C.textFaint }}>{c.ticker} · {c.exchange}</div>
                <div style={{ fontSize: 11.5, color: C.textFaint }}>{c.sector}</div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

/* ----------------------------- SECTION HEADER ----------------------------- */

function SectionHeader({ children, action }) {
  return (
    <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: 12 }}>
      <div style={{ fontSize: 11.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em" }}>{children}</div>
      {action && <button onClick={action.onClick} style={{ border: "none", background: "none", cursor: "pointer", fontSize: 12.5, fontWeight: 600, color: C.text, display: "flex", alignItems: "center", gap: 3 }}>{action.label} <ChevronRight size={12} /></button>}
    </div>
  );
}

/* ----------------------------- PAGE: DASHBOARD ----------------------------- */

function DashboardPage({ followed, goToSearch, goToCompany, setView }) {
  const followedCompanies = Object.values(COMPANIES).filter((c) => followed.has(c.ticker));
  const allChanges = Object.values(COMPANIES).flatMap((c) => c.changes.slice(0, 1).map((ch) => ({ ...ch, company: c })));
  const interesting = Object.values(COMPANIES).filter((c) => !followed.has(c.ticker));

  return (
    <div style={{ maxWidth: 760 }}>
      <div style={{ marginBottom: 8 }}><DemoTag /></div>
      <h1 style={{ fontSize: 22, fontWeight: 700, color: C.text, margin: "10px 0 4px", letterSpacing: "-0.01em" }}>Good morning, Alex</h1>
      <p style={{ fontSize: 14, color: C.textSoft, margin: "0 0 20px" }}>What are you researching today?</p>
      <button onClick={goToSearch} style={{ display: "block", width: "100%", textAlign: "left", border: "none", padding: 0, background: "none", cursor: "pointer" }}>
        <div style={{ pointerEvents: "none" }}><SearchField value="" onChange={() => {}} placeholder="Search a company or ticker" /></div>
      </button>

      <div style={{ marginTop: 36 }}>
        <SectionHeader>YOUR COMPANIES</SectionHeader>
        {followedCompanies.length === 0 ? (
          <p style={{ fontSize: 13, color: C.textFaint }}>You haven't added any companies yet. Try searching for NVIDIA.</p>
        ) : (
          <div>
            {followedCompanies.map((c, i) => (
              <button key={c.ticker} onClick={() => goToCompany(c.ticker)} style={{
                display: "flex", alignItems: "center", width: "100%", textAlign: "left", padding: "13px 4px",
                border: "none", background: "none", cursor: "pointer", borderTop: i === 0 ? `1px solid ${C.border}` : "none", borderBottom: `1px solid ${C.border}`, gap: 12,
              }}>
                <CompanyLogo company={c} size={30} />
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{c.name}</div>
                  <div style={{ fontSize: 11.5, color: C.textFaint }}>Fundamental Score {c.score}</div>
                </div>
                <ChangeTag value={c.scoreChange} />
              </button>
            ))}
          </div>
        )}
      </div>

      <div style={{ marginTop: 32 }}>
        <SectionHeader>RECENT CHANGES</SectionHeader>
        {allChanges.map((ch, i) => (
          <button key={i} onClick={() => goToCompany(ch.company.ticker)} style={{ display: "block", width: "100%", textAlign: "left", border: "none", background: "none", cursor: "pointer", padding: "10px 4px", borderBottom: `1px solid ${C.border}` }}>
            <div style={{ fontSize: 13.5, fontWeight: 600, color: C.text, marginBottom: 2 }}>{ch.company.name}</div>
            <div style={{ fontSize: 12.5, color: C.textSoft, display: "flex", alignItems: "center", gap: 6 }}>
              <ColorDot color={ch.color} /> {ch.metric} improved: {ch.from} → {ch.to}
            </div>
          </button>
        ))}
      </div>

      <div style={{ marginTop: 32, marginBottom: 20 }}>
        <SectionHeader action={{ label: "Discover", onClick: () => setView("discover") }}>INTERESTING COMPANIES</SectionHeader>
        {interesting.length === 0 ? (
          <p style={{ fontSize: 13, color: C.textFaint }}>You're already following everything in this prototype's demo dataset.</p>
        ) : interesting.map((c) => (
          <button key={c.ticker} onClick={() => goToCompany(c.ticker)} style={{ display: "flex", alignItems: "center", gap: 12, width: "100%", textAlign: "left", border: "none", background: "none", cursor: "pointer", padding: "10px 4px", borderBottom: `1px solid ${C.border}` }}>
            <CompanyLogo company={c} size={26} />
            <span style={{ fontSize: 13.5, color: C.text, fontWeight: 500, flex: 1 }}>{c.name}</span>
            <span style={{ fontSize: 13, fontWeight: 700, color: scoreColor(c.score) }}>{c.score}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

/* ----------------------------- CATEGORY DEEP DIVE ----------------------------- */

function CategoryRow({ cat, expanded, onToggle, onViewDetail }) {
  return (
    <div style={{ borderBottom: `1px solid ${C.border}` }}>
      <button onClick={onToggle} style={{ display: "flex", alignItems: "center", width: "100%", padding: "11px 4px", border: "none", background: "none", cursor: "pointer", textAlign: "left", gap: 10 }}>
        <ChevronDown size={13} color={C.textFaint} style={{ transform: expanded ? "rotate(0deg)" : "rotate(-90deg)", transition: "transform 0.15s", flexShrink: 0 }} />
        <span style={{ fontSize: 13.5, color: C.text, fontWeight: 500, flex: 1 }}>{cat.name}</span>
        <div style={{ width: 70, height: 5, backgroundColor: C.bgSecondary, borderRadius: 999, overflow: "hidden" }}>
          <div style={{ width: `${cat.score}%`, height: "100%", backgroundColor: scoreColor(cat.score), borderRadius: 999 }} />
        </div>
        <span style={{ width: 26, textAlign: "right", fontSize: 13.5, fontWeight: 700, color: C.text, fontVariantNumeric: "tabular-nums" }}>{cat.score}</span>
      </button>
      {expanded && (
        <div style={{ padding: "4px 4px 18px 27px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 10, marginBottom: 14 }}>
            {cat.kpis.map((k) => (
              <div key={k.label}>
                <FinancialTerm label={k.label} style={{ fontSize: 11, color: C.textFaint, marginBottom: 2 }} />
                <div style={{ fontSize: 14.5, fontWeight: 600, color: C.text }}>{k.value}</div>
              </div>
            ))}
          </div>
          <div style={{ fontSize: 10.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.05em", marginBottom: 5 }}>WHY IT MATTERS</div>
          <p style={{ fontSize: 12.5, color: C.textSoft, lineHeight: 1.55, margin: "0 0 10px" }}>{cat.why}</p>
          <button onClick={onViewDetail} style={{ border: "none", background: "none", cursor: "pointer", fontSize: 12.5, fontWeight: 600, color: C.text, padding: 0, display: "flex", alignItems: "center", gap: 3 }}>
            View detailed {cat.name.toLowerCase()} analysis <ChevronRight size={12} />
          </button>
        </div>
      )}
    </div>
  );
}

/* ----------------------------- PAGE: COMPANY ----------------------------- */

function CompanyHeader({ company, followed, onToggleFollow }) {
  return (
    <div style={{ marginBottom: 26 }}>
      <div style={{ marginBottom: 14 }}><DemoTag /></div>
      <div style={{ display: "flex", alignItems: "flex-start", gap: 16, flexWrap: "wrap" }}>
        <CompanyLogo company={company} size={52} />
        <div style={{ flex: 1, minWidth: 200 }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap" }}>
            <h1 style={{ fontSize: 22, fontWeight: 700, color: C.text, margin: 0, letterSpacing: "-0.01em" }}>{company.name}</h1>
            <span style={{ fontSize: 13, color: C.textFaint }}>{company.ticker} · {company.exchange}</span>
          </div>
          <div style={{ fontSize: 12.5, color: C.textFaint, marginTop: 2 }}>{company.sector}</div>
          <p style={{ fontSize: 13.5, color: C.textSoft, margin: "8px 0 0", lineHeight: 1.5, maxWidth: 480 }}>{company.description}</p>
        </div>
        <button onClick={onToggleFollow} style={{
          padding: "9px 16px", borderRadius: 8, cursor: "pointer", fontSize: 13, fontWeight: 600, flexShrink: 0,
          border: followed ? `1px solid ${C.border}` : "none", backgroundColor: followed ? C.bg : C.text, color: followed ? C.text : "#fff",
        }}>
          {followed ? "✓ Watchlist" : "+ Add to Watchlist"}
        </button>
      </div>

      <div style={{ marginTop: 22 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: C.textFaint, letterSpacing: "0.06em", marginBottom: 4 }}>FUNDAMENTAL SCORE</div>
        <div style={{ display: "flex", alignItems: "baseline", gap: 10 }}>
          <span style={{ fontSize: 40, fontWeight: 700, color: C.text, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>{company.score}</span>
          <span style={{ fontSize: 12, fontWeight: 700, color: scoreColor(company.score), backgroundColor: scoreSoft(company.score), padding: "3px 9px", borderRadius: 5, letterSpacing: "0.03em" }}>
            {scoreLabel(company.score)}
          </span>
        </div>
      </div>
      <p style={{ fontSize: 11.5, color: C.textFaint, marginTop: 10, maxWidth: 480 }}>
        {company.name}'s fundamentals score {scoreLabel(company.score).toLowerCase()} according to the Equity AI model — this reflects fundamental strength, not a price prediction.
      </p>
    </div>
  );
}

function OverviewTab({ company, goCategoryDeepDive }) {
  const [expandedCat, setExpandedCat] = useState(null);

  return (
    <div>
      <SectionHeader>WHY THIS SCORE</SectionHeader>
      <div>
        {company.categories.map((cat) => (
          <CategoryRow key={cat.key} cat={cat} expanded={expandedCat === cat.key}
            onToggle={() => setExpandedCat(expandedCat === cat.key ? null : cat.key)}
            onViewDetail={() => goCategoryDeepDive(cat)} />
        ))}
      </div>
    </div>
  );
}

function FinancialsTab({ company }) {
  return (
    <div>
      <SectionHeader>KEY FINANCIALS</SectionHeader>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: 16, marginBottom: 30 }}>
        {company.keyFinancials.map((f) => (
          <div key={f.label}>
            <FinancialTerm label={f.label} style={{ fontSize: 11.5, color: C.textFaint, marginBottom: 3 }} />
            <div style={{ fontSize: 18, fontWeight: 700, color: C.text }}>{f.value}</div>
            <SourceNote metricLabel={f.label} company={company} />
          </div>
        ))}
      </div>
      <SectionHeader>ANNUAL HISTORY</SectionHeader>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${C.border}` }}>
              {["Fiscal Year", "Revenue ($B)", "Growth", "Operating Margin", "Free Cash Flow ($B)"].map((h) => (
                <th key={h} style={{ textAlign: "left", padding: "8px 10px 8px 0", fontSize: 11, color: C.textFaint, fontWeight: 700, letterSpacing: "0.03em" }}>
                  <FinancialTerm label={h} />
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {company.financialsHistory.map((row) => (
              <tr key={row.year} style={{ borderBottom: `1px solid ${C.border}` }}>
                <td style={{ padding: "10px 10px 10px 0", fontWeight: 600, color: C.text }}>{row.year}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{row.revenue.toFixed(1)}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.green, fontWeight: 600 }}>+{row.growth}%</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{row.opMargin}%</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{row.fcf.toFixed(1)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p style={{ fontSize: 11, color: C.textFaint, marginTop: 14 }}>Quarterly breakdowns, balance sheet detail, and full growth/margin history would extend this table in production — kept to annual summary for this prototype.</p>
    </div>
  );
}

function ValuationTab({ company }) {
  return (
    <div>
      <SectionHeader>VALUATION MULTIPLES</SectionHeader>
      <div style={{ overflowX: "auto", marginBottom: 30 }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${C.border}` }}>
              {["Multiple", "Current", "Peer Median", "5Y Avg"].map((h) => (
                <th key={h} style={{ textAlign: "left", padding: "8px 10px 8px 0", fontSize: 11, color: C.textFaint, fontWeight: 700, letterSpacing: "0.03em" }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {company.valuation.multiples.map((m) => (
              <tr key={m.label} style={{ borderBottom: `1px solid ${C.border}` }}>
                <td style={{ padding: "10px 10px 10px 0", fontWeight: 600, color: C.text }}>
                  <FinancialTerm label={m.label} />
                </td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{m.value}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.textSoft }}>{m.peerMedian}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.textSoft }}>{m.historicalAvg}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <SectionHeader>PEER COMPARISON</SectionHeader>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${C.border}` }}>
              {["Company", "P/E", "EV / EBITDA"].map((h) => (
                <th key={h} style={{ textAlign: "left", padding: "8px 10px 8px 0", fontSize: 11, color: C.textFaint, fontWeight: 700, letterSpacing: "0.03em" }}>
                  <FinancialTerm label={h} />
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {company.valuation.peers.map((p) => (
              <tr key={p.name} style={{ borderBottom: `1px solid ${C.border}` }}>
                <td style={{ padding: "10px 10px 10px 0", fontWeight: 600, color: C.text }}>{p.name}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{p.pe}</td>
                <td style={{ padding: "10px 10px 10px 0", color: C.text }}>{p.evEbitda}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p style={{ fontSize: 12, color: C.textSoft, lineHeight: 1.5, marginTop: 16, maxWidth: 500 }}>
        Valuation is read alongside growth, profitability and cash generation — not on its own. A lower multiple than peers isn't automatically "cheap," and a higher one isn't automatically "expensive."
      </p>
    </div>
  );
}

function AnalysisTab({ company }) {
  const [thesisCase, setThesisCase] = useState("bull");
  return (
    <div>
      <SectionHeader>AI INVESTMENT THESIS</SectionHeader>
      <p style={{ fontSize: 14, color: C.text, lineHeight: 1.6, margin: "0 0 16px" }}>{company.thesis.summary}</p>
      <div style={{ display: "flex", gap: 4, marginBottom: 12, borderBottom: `1px solid ${C.border}` }}>
        {["bull", "base", "bear"].map((k) => (
          <button key={k} onClick={() => setThesisCase(k)} style={{
            border: "none", background: "none", cursor: "pointer", padding: "6px 12px 10px", fontSize: 12.5, fontWeight: 600,
            color: thesisCase === k ? C.text : C.textFaint, borderBottom: thesisCase === k ? `2px solid ${C.text}` : "2px solid transparent",
            textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: -1,
          }}>
            {k}
          </button>
        ))}
      </div>
      <p style={{ fontSize: 13, color: C.textSoft, lineHeight: 1.55, margin: "0 0 24px" }}>{company.thesis[thesisCase]}</p>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 30 }}>
        <div>
          <div style={{ fontSize: 10.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.05em", marginBottom: 6 }}>RISKS</div>
          <ul style={{ margin: 0, paddingLeft: 16 }}>
            {company.thesis.risks.map((r, i) => <li key={i} style={{ fontSize: 12.5, color: C.textSoft, marginBottom: 5, lineHeight: 1.45 }}>{r}</li>)}
          </ul>
        </div>
        <div>
          <div style={{ fontSize: 10.5, fontWeight: 700, color: C.textFaint, letterSpacing: "0.05em", marginBottom: 6 }}>CATALYSTS</div>
          <ul style={{ margin: 0, paddingLeft: 16 }}>
            {company.thesis.catalysts.map((r, i) => <li key={i} style={{ fontSize: 12.5, color: C.textSoft, marginBottom: 5, lineHeight: 1.45 }}>{r}</li>)}
          </ul>
        </div>
      </div>

      <SectionHeader>WHAT CHANGED</SectionHeader>
      {company.changes.map((ch, i) => (
        <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: `1px solid ${C.border}` }}>
          <ColorDot color={ch.color} />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 13, fontWeight: 500, color: C.text }}>{ch.metric}</div>
            <div style={{ fontSize: 11, color: C.textFaint }}>{ch.date}</div>
          </div>
          <div style={{ fontSize: 12.5, color: C.textFaint, fontVariantNumeric: "tabular-nums" }}>{ch.from} → {ch.to}</div>
        </div>
      ))}
    </div>
  );
}

const TABS = [
  { key: "overview", label: "Overview" },
  { key: "financials", label: "Financials" },
  { key: "valuation", label: "Valuation" },
  { key: "analysis", label: "Analysis" },
];

function CompanyPage({ ticker, followed, onToggleFollow, initialTab, onBack }) {
  const company = COMPANIES[ticker];
  const [activeTab, setActiveTab] = useState(initialTab || "overview");
  if (!company) return null;

  return (
    <div style={{ maxWidth: 640 }}>
      <button onClick={onBack} style={{ display: "flex", alignItems: "center", gap: 4, border: "none", background: "none", cursor: "pointer", color: C.textSoft, fontSize: 13, fontWeight: 500, marginBottom: 16, padding: 0 }}>
        ← Back
      </button>
      <CompanyHeader company={company} followed={followed} onToggleFollow={onToggleFollow} />

      <div style={{ display: "flex", gap: 22, borderBottom: `1px solid ${C.border}`, marginBottom: 26 }}>
        {TABS.map((t) => (
          <button key={t.key} onClick={() => setActiveTab(t.key)} style={{
            border: "none", background: "none", cursor: "pointer", padding: "0 0 11px", fontSize: 13.5, fontWeight: 600,
            color: activeTab === t.key ? C.text : C.textFaint, borderBottom: activeTab === t.key ? `2px solid ${C.text}` : "2px solid transparent", marginBottom: -1,
          }}>
            {t.label}
          </button>
        ))}
      </div>

      {activeTab === "overview" && <OverviewTab company={company} goCategoryDeepDive={(cat) => setActiveTab(cat.tab)} />}
      {activeTab === "financials" && <FinancialsTab company={company} />}
      {activeTab === "valuation" && <ValuationTab company={company} />}
      {activeTab === "analysis" && <AnalysisTab company={company} />}
    </div>
  );
}

/* ----------------------------- OTHER PAGES ----------------------------- */

function ListPage({ title, subtitle, companies, goToCompany, emptyText }) {
  return (
    <div style={{ maxWidth: 640 }}>
      <div style={{ marginBottom: 8 }}><DemoTag /></div>
      <h1 style={{ fontSize: 20, fontWeight: 700, color: C.text, margin: "10px 0 4px" }}>{title}</h1>
      {subtitle && <p style={{ fontSize: 13.5, color: C.textSoft, margin: "0 0 22px" }}>{subtitle}</p>}
      {companies.length === 0 ? (
        <p style={{ fontSize: 13, color: C.textFaint }}>{emptyText}</p>
      ) : companies.map((c, i) => (
        <button key={c.ticker} onClick={() => goToCompany(c.ticker)} style={{
          display: "flex", alignItems: "center", gap: 12, width: "100%", textAlign: "left", padding: "13px 4px",
          border: "none", background: "none", cursor: "pointer", borderTop: i === 0 ? `1px solid ${C.border}` : "none", borderBottom: `1px solid ${C.border}`,
        }}>
          <CompanyLogo company={c} size={32} />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{c.name}</div>
            <div style={{ fontSize: 12, color: C.textFaint }}>{c.ticker} · {c.sector}</div>
          </div>
          <span style={{ fontSize: 15, fontWeight: 700, color: scoreColor(c.score) }}>{c.score}</span>
        </button>
      ))}
    </div>
  );
}

function DiscoverPage({ followed, goToCompany }) {
  const interesting = Object.values(COMPANIES).filter((c) => !followed.has(c.ticker));
  return <ListPage title="Discover" subtitle="Companies worth a closer look, based on this prototype's demo dataset." companies={interesting} goToCompany={goToCompany} emptyText="You're already following everything in this prototype's demo dataset." />;
}

function WatchlistPage({ followed, goToCompany }) {
  const list = Object.values(COMPANIES).filter((c) => followed.has(c.ticker));
  return <ListPage title="Watchlist" subtitle="Companies you're continuously tracking." companies={list} goToCompany={goToCompany} emptyText="You haven't added any companies to your watchlist yet." />;
}

function CompaniesPage({ goToCompany }) {
  return <ListPage title="Companies" subtitle="Every company in this prototype's demo dataset." companies={Object.values(COMPANIES)} goToCompany={goToCompany} emptyText="" />;
}

function AlertsPage({ followed, goToCompany }) {
  const alerts = Object.values(COMPANIES)
    .filter((c) => followed.has(c.ticker))
    .flatMap((c) => c.changes.map((ch) => ({ ...ch, company: c })));

  return (
    <div style={{ maxWidth: 640 }}>
      <div style={{ marginBottom: 8 }}><DemoTag /></div>
      <h1 style={{ fontSize: 20, fontWeight: 700, color: C.text, margin: "10px 0 4px" }}>Alerts</h1>
      <p style={{ fontSize: 13.5, color: C.textSoft, margin: "0 0 22px" }}>Meaningful changes in the companies you follow.</p>
      {alerts.length === 0 ? (
        <p style={{ fontSize: 13, color: C.textFaint }}>No alerts yet — follow a company to start monitoring it.</p>
      ) : alerts.map((a, i) => (
        <button key={i} onClick={() => goToCompany(a.company.ticker)} style={{
          display: "flex", alignItems: "flex-start", gap: 10, width: "100%", textAlign: "left", padding: "13px 4px",
          border: "none", background: "none", cursor: "pointer", borderTop: i === 0 ? `1px solid ${C.border}` : "none", borderBottom: `1px solid ${C.border}`,
        }}>
          <div style={{ marginTop: 4 }}><ColorDot color={a.color} /></div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 13.5, fontWeight: 600, color: C.text }}>{a.company.name}</div>
            <div style={{ fontSize: 12.5, color: C.textSoft, marginTop: 1 }}>{a.metric}: {a.from} → {a.to}</div>
          </div>
          <div style={{ fontSize: 11.5, color: C.textFaint, flexShrink: 0 }}>{a.date}</div>
        </button>
      ))}
    </div>
  );
}

function SettingsPage() {
  return (
    <div style={{ maxWidth: 480 }}>
      <div style={{ marginBottom: 8 }}><DemoTag /></div>
      <h1 style={{ fontSize: 20, fontWeight: 700, color: C.text, margin: "10px 0 4px" }}>Settings</h1>
      <p style={{ fontSize: 13.5, color: C.textSoft, margin: "0 0 22px" }}>Not detailed in the current prototype spec — placeholder only.</p>
      <div style={{ padding: "16px 0", borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}` }}>
        <div style={{ fontSize: 13.5, fontWeight: 600, color: C.text, marginBottom: 2 }}>Account</div>
        <div style={{ fontSize: 12.5, color: C.textFaint }}>Demo user — not connected to a real account.</div>
      </div>
    </div>
  );
}

/* ----------------------------- APP ----------------------------- */

export default function EquityAIPrototype() {
  const [view, setView] = useState("dashboard");
  const [selectedTicker, setSelectedTicker] = useState(null);
  const [companyInitialTab, setCompanyInitialTab] = useState("overview");
  const [followed, setFollowed] = useState(new Set(["NVDA"]));
  const [recentSearches, setRecentSearches] = useState(["NVDA", "MSFT"]);
  const [mobileOpen, setMobileOpen] = useState(false);

  const goToCompany = (ticker, tab) => {
    setSelectedTicker(ticker);
    setCompanyInitialTab(tab || "overview");
    setView("company");
    setRecentSearches((prev) => [ticker, ...prev.filter((t) => t !== ticker)].slice(0, 3));
  };
  const goToSearch = () => setView("search");
  const toggleFollow = (ticker) => {
    setFollowed((prev) => {
      const next = new Set(prev);
      if (next.has(ticker)) next.delete(ticker); else next.add(ticker);
      return next;
    });
  };

  let page;
  if (view === "dashboard") page = <DashboardPage followed={followed} goToSearch={goToSearch} goToCompany={goToCompany} setView={setView} />;
  else if (view === "search") page = <SearchView recentSearches={recentSearches} goToCompany={goToCompany} />;
  else if (view === "company") page = <CompanyPage ticker={selectedTicker} followed={followed.has(selectedTicker)} onToggleFollow={() => toggleFollow(selectedTicker)} initialTab={companyInitialTab} onBack={() => setView("dashboard")} />;
  else if (view === "watchlist") page = <WatchlistPage followed={followed} goToCompany={goToCompany} />;
  else if (view === "companies") page = <CompaniesPage goToCompany={goToCompany} />;
  else if (view === "discover") page = <DiscoverPage followed={followed} goToCompany={goToCompany} />;
  else if (view === "alerts") page = <AlertsPage followed={followed} goToCompany={goToCompany} />;
  else if (view === "settings") page = <SettingsPage />;

  return (
    <div style={{ fontFamily: FONT, backgroundColor: C.bg, minHeight: "100vh", display: "flex", color: C.text }}>
      <Sidebar view={view} setView={setView} />
      <div style={{ flex: 1, minWidth: 0, display: "flex", flexDirection: "column" }}>
        <MobileTopBar view={view} setView={setView} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} />
        <div style={{ flex: 1, padding: "32px 24px 60px" }}>
          {page}
        </div>
      </div>
    </div>
  );
}
